currency_codes = {     
    "dollar": "USD",     
    "euro": "EUR",     
    "british pound sterling": "GBP",     
    "japanese yen": "JPY",     
    "swiss franc": "CHF",     
    "canadian dollar": "CAD",     
    "australian dollar": "AUD",     
    "new zealand dollar": "NZD",     
    "chinese yuan": "CNY",     
    "indian rupee": "INR",     
    "mexican peso": "MXN",     
    "brazilian real": "BRL",     
    "south african rand": "ZAR",     
    "singapore dollar": "SGD",     
    "hong kong dollar": "HKD",     
    "norwegian krone": "NOK",     
    "swedish krona": "SEK",     
    "danish krone": "DKK",     
    "israeli new shekel": "ILS",     
    "russian ruble": "RUB",     
    "south korean won": "KRW",     
    "turkish lira": "TRY",     
    "argentine peso": "ARS",     
    "chilean peso": "CLP",     
    "polish zloty": "PLN",     
    "thai baht": "THB",     
    "indonesian rupiah": "IDR",     
    "malaysian ringgit": "MYR",     
    "philippine peso": "PHP",     
    "egyptian pound": "EGP",     
    "qatari riyal": "QAR",     
    "kuwaiti dinar": "KWD",     
    "bahraini dinar": "BHD",     
    "omani rial": "OMR",     
    "united arab emirates dirham": "AED",     
    "saudi riyal": "SAR",     
    "jordanian dinar": "JOD",     
    "lebanese pound": "LBP",     
    "vietnamese dong": "VND",     
    "czech koruna": "CZK",     
    "hungarian forint": "HUF",     
    "romanian leu": "RON",     
    "bulgarian lev": "BGN",     
    "croatian kuna": "HRK",     
    "serbian dinar": "RSD",     
    "ukrainian hryvnia": "UAH",     
    "kazakhstani tenge": "KZT",     
    "uzbekistani som": "UZS",     
    "tanzanian shilling": "TZS",     
    "kenyan shilling": "KES",     
    "ghanaian cedi": "GHS",     
    "nigerian naira": "NGN",     
    "bangladeshi taka": "BDT",     
    "sri lankan rupee": "LKR"
}
